services:
  - type: web
    name: ai-knowledge-aggregator-backend
    env: node
    plan: free
    buildCommand: npm run install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: ./data/database.sqlite
      - key: FRONTEND_URL
        value: https://your-vercel-domain.vercel.app
